[package]
name = "pixi_auth"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description = "Authentication utilities for pixi"

[features]
default = ["rustls-tls"]
native-tls = ["rattler_networking/native-tls"]
rustls-tls = ["rattler_networking/rustls-tls"]

[dependencies]
pixi_config = { workspace = true }
rattler_networking = { workspace = true, features = ["system-integration"] }
tracing = { workspace = true }
