[package]
name = "pixi_diff"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
ahash = { workspace = true }
console = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
pixi_consts = { workspace = true }
pixi_manifest = { workspace = true }
rattler_conda_types = { workspace = true }
rattler_lock = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tabwriter = { workspace = true }
